### ISSUE TITLE
Decimals in Baseliner extension

### ISSUE THREAD

**Issue by izelnakri** [jpedroribeiro/Baseliner#1]
Bootstrap 4 navigation height is 54px. I would really like to set the baseline 13,5 px. Could you please add this feature to baseliner?

**Comment by jpedroribeiro** [comment]
I'm using canvas to generate the image and sadly it only seem to accept round numbers (int) as parameter. Any floating point result in a blank image.

**Comment by borracciaBlu** [comment]
read here:
http://stackoverflow.com/questions/4308989/are-the-decimal-places-in-a-css-width-respected  
http://jsfiddle.net/q5BQs/3/

So probably when someone uses 15.6 we should use 16.
