### ISSUE TITLE
Baseliner is turned off & settings reset on each new page

### ISSUE THREAD

**Issue by axertion** [jpedroribeiro/Baseliner#10]
I figured I'd add a new issue which is related to this closed one:
https://github.com/jpedroribeiro/Baseliner/issues/9

Baseliner doesn't persist through different pages on a site.  So if you click a link or navigate throughout the website, Baseliner gets disabled and reset.

This makes Baseliner practically useless now for testing a website because you have to re-enable it, and then re-input the settings for every single page.

For some reason, this doesn't happen when using Baseliner on Github.

**Comment by axertion** [comment]
To persist the settings for the domain, I discovered that we can use `window.location.origin` Instead of `window.location.href` to save the settings to the Chrome cache.

That fixes the main issue of the settings not persisting.  The other problem is that Baseliner doesn't remain open when navigating.  So if you click on a link, Baseliner closes and you have to reopen then apply all over again.

**Comment by jpedroribeiro** [comment]
Yes, I'm currently using the full URL to create a primary index on local storage. 
I guess it would make more sense to save setting per **domain** (i.e.: wikipedia.org) rather than per **url** (i.e.: wikipedia.org/wiki/Lists_of_films) as the grid would remain the same throughout the domain. I'll take note and make this change on **next release**.

Regarding your second point, that is just the default behaviour of a Chrome Extension - as soon as you lose focus the extension closes.

**Comment by axertion** [comment]
Can you use something like [content_scripts](https://developer.chrome.com/extensions/content_scripts) in which you can run a JS file on each page and initialize Baseliner automatically if you detect it was active?
```
  "content_scripts": [
  {
    "matches": ["<all_urls>"],
    "js": ["activateBaseliner.js"]
  }
```

That might not be the _best_ way, but certainly there must be some way to automatically carry the grid lines from page to page.

I'll see if I can figure something out when I get the time and post back my findings (perhaps even submit a PR)

**Comment by jpedroribeiro** [comment]
As far as I can see on the documentation, _content_scripts_ dont allow you to access **storage**, which is where we keep the Baseliner details for a specific page.

I'll definitely welcome a PR on this!

**Comment by kbrock** [comment]
For some reason, `window.location.origin` isn't working for me.

The load is finding the values, which is good.
But it resets the values, which is not so good

**Comment by jpedroribeiro** [comment]
Could you elaborate it a bit more? It loads the values that were previously saved but then _resets_ them? Also, which Chrome version are we talking about?

**Comment by kbrock** [comment]
@jpedroribeiro ignore that. Installed a recent version and it seems to be remembering the location.
