### ISSUE TITLE
Better guessing of the line-height

### ISSUE THREAD

**Issue by kbrock** [jpedroribeiro/Baseliner#12]
Is there a way to detect the line-height from the document?
Maybe multiply the `line-height` by `font-size` from the `html` or `body` elements?

It seems like it would be impossible to get perfect, but possibly easier to get close.

**Comment by jpedroribeiro** [comment]
Considering the nature of CSS, there is a lot of guesswork involved to figure out the grid based on those properties. I don't think we would be able to achieve a consistency experience.

I guess in the end I'd rather start Baseliner out with a default value and let the user go from there.

Thanks for the suggestion tho 😉

**Comment by kbrock** [comment]
Thanks again for the great tool
