### ISSUE TITLE
Regression: Cannot specify offset

### ISSUE THREAD

**Issue by rudolfbyker** [jpedroribeiro/Baseliner#16]
For sites where the rhythm starts lower on the page, because of some banner or image at the top, we need to be able to specify an offset. This was possible in recent versions of Baseliner, but is missing from newer versions.

**Comment by jpedroribeiro** [comment]
Yes, this is on my TODO list. I'll try to get it done and published by the weekend/early next week.
Thanks for the feedback.

**Comment by jpedroribeiro** [comment]
This was fixed on version 6.1.
