### ISSUE TITLE
New version does not work on localhost

### ISSUE THREAD

**Issue by steida** [jpedroribeiro/Baseliner#18]
I don't know why, but when I click to the icon, popup quickly disappears.

**Comment by shurfee** [comment]
Not working everywhere, not only localhost. Same problem

**Comment by jpedroribeiro** [comment]
Would you mind giving it a check once again? I've literally just pushed version 6.2 with some updates and I wonder if it's fixed on your end. (c @shurfee + @steida )

**Comment by shurfee** [comment]
It works now! And you add vertical lines - that`s awesome! Thank you!

**Comment by steida** [comment]
Yep. Thank you for the fix and for the useful tool.
