### ISSUE TITLE
Baseliner styles not loaded on local environment

### ISSUE THREAD

**Issue by tbreuss** [jpedroribeiro/Baseliner#24]
On a local development environment sometimes (or maybe always) the Baseliner styles will not be loaded.

<img width="1090" alt="baseliner-local-dev" src="https://user-images.githubusercontent.com/1334161/97689306-aa0a8000-1a9b-11eb-9619-9a1a2a2a4086.png">

- Version: 6.3
- Chrome: 87.0.4280.27
- OS: MacOS 10.14.6 (18G6032)

**Comment by tbreuss** [comment]
Me again.

- It doesn't work if the HTML file is opended via browser (without a webserver)
- It works if the file is opened via a local driven webserver

So, maybe this is not really an issue.

**Comment by jpedroribeiro** [comment]
Yeah you're right, **Baseliner** (or any other extension) won't work if you open a file in your browser. It's a **browser security** feature to prevent extensions to having access to your file system (the`file://` protocol).

If you **really** need to use it this way, the only way I can think of is downloading the source code, running `yarn build`, and then loading the unpacked version via developer mode under `chrome://extensions/`. If you ask me, it's easier just running a local server.
