### ISSUE TITLE
Request: Have the option to show shaded panels rather than lines

### ISSUE THREAD

**Issue by mfb-remotesocial** [jpedroribeiro/Baseliner#26]
Figma has the ability to show filled columns of colour rather than thin lines of a grid... this could be a good option to help view alignment.

**Comment by patrickplaggenborg** [comment]
Looking for exactly the same. For example, a 4px baseline grid with a 4px zebra stripping.

A simple setting to set the width of the lines in Baseliner would allow you to use it this way.

<img width="897" alt="figma baseline grid example" src="https://user-images.githubusercontent.com/2269563/138877444-2b595df7-98a1-415d-90a9-02b339d03056.png">

**Comment by patrickplaggenborg** [comment]
The extension is set up in a very smart way, by using overlay gradients to create patterns.

Should be quite easy by adjusting the CSS for `.baseline::after` to something like:

`background: linear-gradient(rgba(205, 77, 40, 0.14) 4px, transparent 4px) left top / 100% 8px repeat-y`

**Comment by jpedroribeiro** [comment]
Thanks for the suggestion @patrickplaggenborg and @mfb-remotesocial , I've just published an update to Baseliner with this idea. It's a bit experimental so feel free to post any feedback.

FireFox version is out today. Chrome release takes a few days to publish so bear with.
