### ISSUE TITLE
UI/UX Issues in Firefox version

### ISSUE THREAD

**Issue by manuelmoreale** [jpedroribeiro/Baseliner#36]
I want to flag a UI issue and one UX issue with the Firefox version of the plugin.
The UI is related to the offset panel where the native controls to increase/decrease the value of the input are making impossible to input a number manually and to see the value (see screenshot)

![Screenshot 2021-08-19 at 9 11 56 AM](https://user-images.githubusercontent.com/1738077/130024712-99ac1b59-0f0e-4e6d-9a8e-fc8262f98a72.png)

The UX one is related to the color picker.
On Firefox on Mac, clicking on the color opens up the native Mac color picker and within that it's impossible to actually pick a color.

**Comment by jpedroribeiro** [comment]
This has been fixed on release 6.4 - make sure to update your add-on.
