### ISSUE TITLE
Feature request: Storybook addon

### ISSUE THREAD

**Issue by patrickplaggenborg** [jpedroribeiro/Baseliner#42]
Unfortunately Baseliner does not work in Storybook. Also, the canvas in storybook is not exactly a multiple of your grid space (i.e. 4px) from the top of the browser viewport.

Would be amazing to have a storybook addon that would be able to toggle Baseliner on/off on the Canvas only.

<img width="757" alt="baseliner toggle" src="https://user-images.githubusercontent.com/2269563/145786059-27972b3e-8a37-4751-adf0-27f65dc0b4d0.png">

**Comment by jpedroribeiro** [comment]
I believe that this bugfix (https://github.com/jpedroribeiro/Baseliner/commit/1152e455aaa5c051734287c24c5538162057ac61) might also fix your use case (at least it did on other instances of Storybook).

You'll need the freshly published Baseliner v7.0.

Thanks for the suggestion of making a Storybook add-on, I'll have a thing about it.
