### ISSUE TITLE
Extension breaks vertically centered page when enabled

### ISSUE THREAD

**Issue by johnknoop** [jpedroribeiro/Baseliner#43]
I believe this is related to the fact that this page is vertically centered (using flex), because I've used this extension on other sites without any problems.

Here's what happens when I turn on the extension:

![baseliner](https://user-images.githubusercontent.com/3394270/147093322-24c9a938-7b8c-42f8-a817-722c2ecb55c3.gif)

It seems to be caused by the `body` element getting `height: auto;` when the extension is enabled.

**Comment by jpedroribeiro** [comment]
You're right, that `body` style is not even needed anymore. 
This was fixed with https://github.com/jpedroribeiro/Baseliner/commit/4a7f3e1d4eb3716b268c8747278061ef2150ffbb and published to Chrome store. Hopefully they'll approve it soon.

Thanks for the feedback.
