### ISSUE TITLE
Request: Persist Baseliner Settings

### ISSUE THREAD

**Issue by axertion** [jpedroribeiro/Baseliner#9]
Baseliner is by far the nicest Chrome extension I've found when it comes to simply laying out a baseline grid over a web-page.

It's pretty annoying however that the settings I put into Baseliner aren't saved/persisted when I reopen it, forcing me to have to re-enter the defaults I use for my site each time.

Any chance the settings could get saved into local storage and persisted?

**Comment by jpedroribeiro** [comment]
I like the idea! 
I'll put my thinking hat and see if I can come up with something ;-)

**Comment by axertion** [comment]
Awesome! 👍

**Comment by jpedroribeiro** [comment]
Just pushed a new version with your idea in place. 
Go to [chrome:extensions](url) and make sure your Baseliner is v5.3 (it can take some time for Google Store to propagate the update).

Give it a try and let me know what you think or if you find any bugs.

**Comment by axertion** [comment]
It works, but the settings only persist for a single page.  As soon as I click to a new page, the settings are wiped and baseliner is turned off making the persistence kind of useless!

It'd be better if once turned on, Baseliner stays on for all pages on a website, and the settings are persisted for the domain.
